 
pipeline {
   agent {
        docker { image 'node:16.13.1-alpine' }
    }
    triggers {
        pollSCM '* * * * *'
    }
    environment { 
        registry = "nagabhushanamn/ui-service" 
        registryCredential = 'docker-hub' 
        dockerImage = '' 
    }
    stages {
        // CI
        stage('Install dependencies') { 
            steps {
                dir("ui-service"){
                    sh 'npm install'
                }
            }
        }
        stage('Test') { 
            steps {
                dir("ui-service"){
                    // sh 'npm run ci-test'
                    sh 'echo TEST'
                }
            }
        }
        stage('Production-Build') { 
            steps {
                dir("ui-service"){
                    sh 'npm run build'
                }
            }
        }

        stage('Upload to AWS') {
              steps {
                  dir("ui-service"){
                    withAWS(region:'ap-south-1',credentials:'aws-s3-upload') {
                       s3Upload(file:'dist/ui-service', bucket:'nagcloudlab-ui-service', path:'.')
                    }
                  }
              }
         }
        

    //     stage('docker:build') {
    //         steps {
    //             dir("ui-service"){
    //                 script { 
    //                     dockerImage = docker.build registry + ":$BUILD_NUMBER" 
    //                 }
    //             }
    //         }
    //     }
    //     stage('docker:push') {
    //         steps {
    //             script { 
    //                 docker.withRegistry('', registryCredential ) { 
    //                     dockerImage.push() 
    //                 }
    //             } 
    //         }
    //     }
    //     stage('Cleaning up') { 
    //         steps { 
    //             sh "docker rmi $registry:$BUILD_NUMBER" 
    //         }
    //     } 
    // }
    // post {
    //     always {
    //         emailext body: 'Jenkisn build status', subject: 'TEST', to: 'nagcloudlab@gmail.com'
    //     }
    }
}